const user = [
  {
    id: 1,
    FirstName: "Anjana",
    LastName: "Bhattrai",
    DOB: "1999/5/14",
    PrimaryEmail: "anzanabtr2016@gmail.com",
    PrimaryPhoneNumber: 9841086766,
    HighestLevelOfEducation: "Bacheolars",
    GraduatedOn: 2022,
    ReferredBy: "self",
    CVUrl: "cv.com",
    ProfilePictureUrl: "pp.com",
    IsBlacklisted: false,
    BlacklistedReason: "none",
    ExperienceInMonthsWithCompanyName: "fresher",
    ExpectedSalary: 15000,
  },
  {
    id: 2,
    FirstName: "John",
    LastName: "Doe",
    DOB: "1985/10/20",
    PrimaryEmail: "johndoe@example.com",
    PrimaryPhoneNumber: 9876543210,
    HighestLevelOfEducation: "Masters",
    GraduatedOn: 2010,
    ReferredBy: "Friend",
    CVUrl: "cv2.com",
    ProfilePictureUrl: "pp2.com",
    IsBlacklisted: false,
    BlacklistedReason: "none",
    ExperienceInMonthsWithCompanyName: "Acme Corp",
    ExpectedSalary: 50000,
  },
  {
    id: 3,
    FirstName: "Emily",
    LastName: "Johnson",
    DOB: "1992/7/8",
    PrimaryEmail: "emily@example.com",
    PrimaryPhoneNumber: 8765432109,
    HighestLevelOfEducation: "Doctorate",
    GraduatedOn: 2018,
    ReferredBy: "Colleague",
    CVUrl: "cv3.com",
    ProfilePictureUrl: "pp3.com",
    IsBlacklisted: true,
    BlacklistedReason: "Late submissions",
    ExperienceInMonthsWithCompanyName: "Tech Innovators",
    ExpectedSalary: 80000,
  },
  {
    id: 4,
    FirstName: "Emma",
    LastName: "Smith",
    DOB: "1992/8/10",
    PrimaryEmail: "emma.smith@example.com",
    PrimaryPhoneNumber: 9876543210,
    HighestLevelOfEducation: "PhD",
    GraduatedOn: 2018,
    ReferredBy: "colleague",
    CVUrl: "cv.com/emmasmith",
    ProfilePictureUrl: "pp.com/emmasmith",
    IsBlacklisted: true,
    BlacklistedReason: "disciplinary issues",
    ExperienceInMonthsWithCompanyName: "Tech Innovators",
    ExpectedSalary: 75000,
  },
  {
    id: 5,
    FirstName: "Michael",
    LastName: "Johnson",
    DOB: "1988/11/5",
    PrimaryEmail: "michael.johnson@example.com",
    PrimaryPhoneNumber: 8765432109,
    HighestLevelOfEducation: "Bachelors",
    GraduatedOn: 2012,
    ReferredBy: "family member",
    CVUrl: "cv.com/michaeljohnson",
    ProfilePictureUrl: "pp.com/michaeljohnson",
    IsBlacklisted: false,
    BlacklistedReason: "none",
    ExperienceInMonthsWithCompanyName: "Innovate IT Solutions",
    ExpectedSalary: 60000,
  },
  {
    id: 6,
    FirstName: "Sophia",
    LastName: "Lee",
    DOB: "2000/2/18",
    PrimaryEmail: "sophia.lee@example.com",
    PrimaryPhoneNumber: 7654321098,
    HighestLevelOfEducation: "Bachelors",
    GraduatedOn: 2021,
    ReferredBy: "online job portal",
    CVUrl: "cv.com/sophialee",
    ProfilePictureUrl: "pp.com/sophialee",
    IsBlacklisted: false,
    BlacklistedReason: "none",
    ExperienceInMonthsWithCompanyName: "E-Commerce Co.",
    ExpectedSalary: 25000,
  },
];
export default user;
